### ISSUE TITLE
make  cpu in readme.md should be make cpp

### ISSUE THREAD

**Issue by ghost** [fuweixiao/cuda_inpainting#1]
make  cpu in readme.md should be make cpp Or the other way round.

all: cpp cuda

.PHONY: clean cpp cuda
cpp: 
    -$(MAKE) -C ./cpp/

cuda:
    -$(MAKE) -C ./cuda/

clean:
    -$(MAKE) -C ./cpp/ clean
    -$(MAKE) -C ./cuda/ clean

**Comment by fuweixiao** [comment]
Thanks, fixed
